### ISSUE TITLE
Question about Error Code

### ISSUE THREAD

**Issue by nickiemitch** [VIS-2129-F2020/nmitch-vis#3]
Good morning,
Thanks for your help! Here's the code that is getting the error message. The chunk we discussed was {r subset bikeshares with bus} but it happens on all of the similar chunks.

https://vis-2129-f2020.github.io/nmitch-vis/Assignment3

**Comment by bauranov** [comment]
Now I see. You executed the chunk once, and it worked. When you try to rerun it, you are trying to join bike_bus2 with the new data frame. In that case, there is a Name.y column in both data frames. When you do join(), R will add both Name.y's to your resulting indy_bus_stops. Since you can't have two columns with the same name in one data frame, they will be renamed to name.y.x and name.y.y. Then, when you try mutate(something = name.y), R can't find name.y because it doesn't exist anymore.
